### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by jazibobs** [ConnieZhou/Personal-Profile#1]
Hey Connie! 

I'm glad you're finding the time to poke around GitHub. If you rename this repository so it is the same as your username (ConnieZhou/ConnieZhou) then the readme information will turn up on your GitHub profile.

You can see how Yan has done it here: https://github.com/Yanz1213/Yanz1213

Have a good weekend, see you in class!

**Comment by ConnieZhou** [comment]
Okay will do! You too have a good weekend😃

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jared Rigby <notifications@github.com>
发送时间: Saturday, August 22, 2020 3:22:38 PM
收件人: ConnieZhou/Personal-Profile <Personal-Profile@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [ConnieZhou/Personal-Profile] Change repo name (#1)

WARNING: This email originated from an external organization.
DO NOT click any links or attachments unless you trust the sender.

Hey Connie!

I'm glad you're finding the time to poke around GitHub. If you rename this repository so it is the same as your username (ConnieZhou/ConnieZhou) then the readme information will turn up on your GitHub profile.

You can see how Yan has done it here: https://github.com/Yanz1213/Yanz1213

Have a good weekend, see you in class!
